name: unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        wget -O z3.zip "https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/z3-4.8.10-x64-ubuntu-16.04.zip"
        unzip z3.zip
        cp z3*/bin/z3 bin_solvers
        chmod +x bin_solvers/z3
        rm z3.zip
        rm -rf z3*/
        echo "z3 binary downloaded and installed successfully!"
    - name: Running unit test
      run: |
        python -m pytest -m "not slow" -x arlib/tests

